
- hosts: leaf
  connection: httpapi
  gather_facts: false
  collections:
    - dellemc.enterprise_sonic
  

  tasks: 
    - include_vars:
        file: group_vars/vlans.yaml
        name: myvars

    - name: Show yaml var for debug purpose
      debug:
        msg: "{{ myvars }}"

    - name: Push vlans configuration with custom jinja2 scripting
      vars:
        ansible_connection: network_cli
      sonic_config:
          src: templates/vlans.j2
      register: result
    
    - name: Save config
      vars:
        ansible_connection: network_cli
      sonic_config:
        save: no

