is_border_leaf: true
lacp_pcs:
  - 10
mclag_member_pcs:
  - lag: PortChannel10
sonic_bgp:
  - bestpath:
      as_path:
        multipath_relax: true
    bgp_as: '{{ bgp_asn }}'
    router_id: '{{ bgp_router_id }}'
  - bgp_as: '{{bgp_asn}}'
    vrf_name: Vrf1
  - bgp_as: '{{ bgp_asn }}'
sonic_bgp_af:
  - address_family:
      afis:
        - afi: ipv4
          max_path:
            ebgp: 2
          redistribute:
            - protocol: connected
          safi: unicast
        - advertise_all_vni: true
          afi: l2vpn
          safi: evpn
    bgp_as: '{{bgp_asn}}'
  - address_family:
      afis:
        - advertise_prefix:
            - afi: ipv4
              safi: unicast
          afi: l2vpn
          safi: evpn
        - afi: ipv4
          redistribute:
            - protocol: connected
          safi: unicast
    bgp_as: '{{ bgp_asn }}'
    vrf_name: Vrf1
sonic_bgp_neighbors:
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - neighbor: Eth1/9
        peer_group: spine-leaf
      - neighbor: Eth1/8
        peer_group: spine-leaf
    peer_group:
      - '{{sonic_bgp_spineleaf_peergroup}}'
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - neighbor: 2.0.1.2
        remote_as:
          peer_as: 65500
    vrf_name: Vrf1
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - neighbor: 2.0.2.2
        remote_as:
          peer_as: 65500
    vrf_name: Vrf1
sonic_bgp_neighbors_af:
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - address_family: '{{sonic_bgp_fabriclink_neighbors_aflist}}'
        neighbor: Eth1/9
      - address_family: '{{sonic_bgp_fabriclink_neighbors_aflist}}'
        neighbor: Eth1/8
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - address_family:
          - activate: true
            afi: ipv4
            safi: unicast
        neighbor: 2.0.1.2
    vrf_name: Vrf1
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - address_family:
          - activate: true
            afi: ipv4
            safi: unicast
        neighbor: 2.0.2.2
    vrf_name: Vrf1
sonic_config:
  lines: []
sonic_interfaces:
  - description: '"Uplink ext-br1"'
    enabled: true
    name: Eth1/4
  - description: '"Uplink ext-br2"'
    enabled: true
    name: Eth1/5
  - description: '"Node-01_eth1-NDC1-10G-2"'
    enabled: true
    name: Eth1/1
  - description: '"MCLAG to sonic-LEAF-1 Eth1/6"'
    enabled: true
    name: Eth1/6
  - description: '"MCLAG to sonic-LEAF-1 Eth1/7"'
    enabled: true
    name: Eth1/7
  - description: '"Uplink to sonic-SPINE-2 Eth1/2"'
    enabled: true
    name: Eth1/9
  - description: '"Uplink to sonic-SPINE-1 Eth1/2"'
    enabled: true
    name: Eth1/8
  - description: router-id
    name: '{{ loopback_inf0 }}'
  - description: vtep
    name: '{{ loopback_inf1 }}'
  - description: '"LAG to CC1_Node-01_bond0"'
    mtu: 9216
    name: PortChannel10
sonic_l2_interfaces:
  - name: PortChannel 10
    trunk:
      allowed_vlans:
        - vlan: 999
        - vlan: 1011
        - vlan: 1012
  - name: PortChannel100
    trunk:
      allowed_vlans:
        - vlan: 999
        - vlan: 1011
        - vlan: 1012
        - vlan: 60
sonic_l3_interfaces:
  - ipv6:
      enabled: true
    name: Eth1/8
  - ipv6:
      enabled: true
    name: Eth1/9
  - ipv4:
      addresses:
        - address: '{{ loopback0_ip }}'
    name: '{{ loopback_inf0 }}'
  - ipv4:
      addresses:
        - address: '{{ loopback1_ip }}'
    name: '{{ loopback_inf1 }}'
  - ipv4:
      addresses:
        - address: 2.0.1.3/31
    name: Eth1/4
  - ipv4:
      addresses:
        - address: 2.0.2.3/31
    name: Eth1/5
sonic_lag_interfaces:
  - members:
      interfaces:
        - member: Eth1/1
    mode: lacp
    name: PortChannel10
  - members:
      interfaces:
        - member: Eth1/6
        - member: Eth1/7
    name: PortChannel100
sonic_system:
  anycast_address:
    ipv4: true
    mac_address: '{{ anycast_mac_address }}'
  hostname: sonic-LEAF-2
  interface_naming: standard
sonic_vlans:
  - vlan_id: 999
  - vlan_id: 1011
  - vlan_id: 1012
  - vlan_id: 60
sonic_vrf_interfaces:
  - members:
      interfaces:
        - name: Vlan999
        - name: Vlan60
        - name: Vlan1011
        - name: Vlan1012
        - name: Eth1/4
        - name: Eth1/5
    name: Vrf1
sonic_vxlans:
  - evpn_nvo: nvo1
    name: vtep1
    source_ip: '{{ loopback1_ip.split(''/'')[0] }}'
    vlan_map:
      - vlan: 999
        vni: 9990
      - vlan: 1011
        vni: 10110
      - vlan: 1012
        vni: 10120
      - vlan: 60
        vni: 600
    vrf_map:
      - vni: 600
        vrf: Vrf1
vlans:
  - 999
  - 1011
  - 1012
vrfs:
  - Vrf1
