is_border_leaf: false
lacp_pcs:
  - 10
mclag_member_pcs:
  - lag: PortChannel10
sonic_bgp:
  - bestpath:
      as_path:
        multipath_relax: true
    bgp_as: '{{ bgp_asn }}'
    router_id: '{{ bgp_router_id }}'
  - bgp_as: '{{bgp_asn}}'
    vrf_name: Vrf1
  - bgp_as: '{{ bgp_asn }}'
    timers:
      holdtime: 9
      keepalive_interval: 3
sonic_bgp_af:
  - address_family:
      afis:
        - afi: ipv4
          max_path:
            ebgp: 2
          redistribute:
            - protocol: connected
          safi: unicast
        - advertise_all_vni: true
          afi: l2vpn
          safi: evpn
    bgp_as: '{{bgp_asn}}'
  - address_family:
      afis:
        - advertise_prefix:
            - afi: ipv4
              safi: unicast
          afi: l2vpn
          safi: evpn
        - afi: ipv4
          redistribute:
            - protocol: connected
          safi: unicast
    bgp_as: '{{ bgp_asn }}'
    vrf_name: Vrf1
sonic_bgp_neighbors:
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - neighbor: Eth1/1
        peer_group: spine-leaf
      - neighbor: Eth1/5
        peer_group: spine-leaf
    peer_group:
      - '{{sonic_bgp_spineleaf_peergroup}}'
sonic_bgp_neighbors_af:
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - address_family: '{{sonic_bgp_fabriclink_neighbors_aflist}}'
        neighbor: Eth1/1
      - address_family: '{{sonic_bgp_fabriclink_neighbors_aflist}}'
        neighbor: Eth1/5
sonic_config:
  lines: []
sonic_interfaces:
  - description: '"Node-02_eth1-NDC1-10G-2"'
    enabled: true
    name: Eth1/4
  - description: '"MCLAG to sonic-LEAF-3 Eth1/6"'
    enabled: true
    name: Eth1/3
  - description: '"MCLAG to sonic-LEAF-3 Eth1/7"'
    enabled: true
    name: Eth1/7
  - description: '"Uplink to sonic-SPINE-2 Eth1/4"'
    enabled: true
    name: Eth1/5
  - description: '"Uplink to sonic-SPINE-1 Eth1/4"'
    enabled: true
    name: Eth1/1
  - description: 'router-id'
    name: '{{ loopback_inf0 }}'
  - description: 'vtep'
    name: '{{ loopback_inf1 }}'
  - description: '"LAG to CC1_Node-02_bond0"'
    mtu: 9216
    name: PortChannel10
sonic_l2_interfaces:
  - name: PortChannel 10
    trunk:
      allowed_vlans:
        - vlan: 999
        - vlan: 1010
        - vlan: 1020
  - name: PortChannel100
    trunk:
      allowed_vlans:
        - vlan: 999
        - vlan: 1010
        - vlan: 1020
        - vlan: 60
sonic_l3_interfaces:
  - ipv6:
      enabled: true
    name: Eth1/1
  - ipv6:
      enabled: true
    name: Eth1/5
  - ipv4:
      addresses:
        - address: '{{ loopback0_ip }}'
    name: '{{ loopback_inf0 }}'
  - ipv4:
      addresses:
        - address: '{{ loopback1_ip }}'
    name: '{{ loopback_inf1 }}'
sonic_lag_interfaces:
  - members:
      interfaces:
        - member: Eth1/4
    mode: lacp
    name: PortChannel10
  - members:
      interfaces:
        - member: Eth1/3
        - member: Eth1/7
    name: PortChannel100
sonic_system:
  anycast_address:
    ipv4: true
    mac_address: '{{ anycast_mac_address }}'
  hostname: sonic-LEAF-4
  interface_naming: standard
sonic_vlans:
  - vlan_id: 999
  - vlan_id: 1010
  - vlan_id: 1020
  - vlan_id: 60
sonic_vrf_interfaces:
  - members:
      interfaces:
        - name: Vlan999
        - name: Vlan60
        - name: Vlan1010
        - name: Vlan1020
    name: Vrf1
sonic_vxlans:
  - evpn_nvo: nvo1
    name: vtep3
    source_ip: '{{ loopback1_ip.split(''/'')[0] }}'
    vlan_map:
      - vlan: 999
        vni: 9990
      - vlan: 1010
        vni: 10100
      - vlan: 1020
        vni: 10200
      - vlan: 60
        vni: 600
    vrf_map:
      - vni: 600
        vrf: Vrf1
vlans:
  - 999
  - 1010
  - 1020
vrfs:
  - Vrf1
